export type SafetyLevel = 'safe' | 'caution' | 'toxic' | 'deadly';

export interface FoodItem {
  name: string;
  emoji: string;
  category: string;
  image?: string;
  dog: {
    safety: SafetyLevel;
    note: string;
  };
  cat: {
    safety: SafetyLevel;
    note: string;
  };
}

export const FOOD_DATABASE: FoodItem[] = [
  // === FRUITS ===
  { name: "Apples", emoji: "🍎", category: "Fruits",
    dog: { safety: "safe", note: "Remove seeds and core. The flesh is a great low-calorie snack rich in vitamins A and C." },
    cat: { safety: "safe", note: "Small amounts are fine. Remove seeds, which contain cyanide compounds." }},
  { name: "Bananas", emoji: "🍌", category: "Fruits",
    dog: { safety: "safe", note: "High in potassium and vitamins. Feed in moderation due to sugar content." },
    cat: { safety: "caution", note: "Not toxic, but high in sugar. Most cats aren't interested. Small bites only." }},
  { name: "Blueberries", emoji: "🫐", category: "Fruits",
    dog: { safety: "safe", note: "Excellent superfood treat! Rich in antioxidants and fiber." },
    cat: { safety: "safe", note: "Safe in small amounts. A good source of vitamins and antioxidants." }},
  { name: "Grapes", emoji: "🍇", category: "Fruits",
    dog: { safety: "deadly", note: "EXTREMELY TOXIC. Even small amounts can cause acute kidney failure. Seek emergency vet care immediately." },
    cat: { safety: "toxic", note: "Toxic to cats as well. Can cause kidney damage. Avoid completely." }},
  { name: "Raisins", emoji: "🍇", category: "Fruits",
    dog: { safety: "deadly", note: "EXTREMELY TOXIC — even more concentrated than grapes. A tiny amount can be fatal. Emergency vet NOW." },
    cat: { safety: "deadly", note: "Highly toxic. Even small amounts can cause kidney failure. Seek emergency care." }},
  { name: "Watermelon", emoji: "🍉", category: "Fruits",
    dog: { safety: "safe", note: "Remove seeds and rind. The flesh is hydrating and rich in vitamins A, B6, and C." },
    cat: { safety: "safe", note: "Safe in small amounts. Remove seeds and rind first." }},
  { name: "Strawberries", emoji: "🍓", category: "Fruits",
    dog: { safety: "safe", note: "Full of fiber and vitamin C. Cut into small pieces to prevent choking." },
    cat: { safety: "safe", note: "Non-toxic but most cats won't eat them. Fine as an occasional treat." }},
  { name: "Oranges", emoji: "🍊", category: "Fruits",
    dog: { safety: "caution", note: "Flesh is safe in small amounts. Peel and seeds can cause GI upset. High sugar." },
    cat: { safety: "caution", note: "The citric acid and oils can cause stomach upset. Most cats dislike citrus." }},
  { name: "Cherries", emoji: "🍒", category: "Fruits",
    dog: { safety: "toxic", note: "Stems, leaves, and pits contain cyanide. The flesh is safe but not worth the risk." },
    cat: { safety: "toxic", note: "Pits, stems, and leaves are toxic. Avoid entirely." }},
  { name: "Avocado", emoji: "🥑", category: "Fruits",
    dog: { safety: "caution", note: "The flesh is mildly safe but the pit, skin, and leaves contain persin which is toxic. Best avoided." },
    cat: { safety: "toxic", note: "Contains persin which can cause vomiting and diarrhea in cats. Avoid." }},
  { name: "Mangoes", emoji: "🥭", category: "Fruits",
    dog: { safety: "safe", note: "Remove the pit and peel. The flesh is packed with vitamins. Feed in moderation." },
    cat: { safety: "safe", note: "Small amounts of flesh are fine. Remove pit and skin." }},
  { name: "Pineapple", emoji: "🍍", category: "Fruits",
    dog: { safety: "safe", note: "Fresh pineapple in small chunks is fine. Avoid canned (too much sugar). Remove skin and core." },
    cat: { safety: "caution", note: "Small amounts won't hurt, but the acidity can upset their stomach." }},
  { name: "Peaches", emoji: "🍑", category: "Fruits",
    dog: { safety: "caution", note: "Flesh is safe. The pit contains cyanide and is a choking hazard — always remove it." },
    cat: { safety: "caution", note: "Flesh is okay in small amounts. Always remove the pit." }},
  { name: "Coconut", emoji: "🥥", category: "Fruits",
    dog: { safety: "safe", note: "Coconut flesh and oil are safe and can benefit skin/coat. Avoid the shell." },
    cat: { safety: "caution", note: "Small amounts are okay. Coconut milk and oil can cause digestive upset." }},

  // === VEGETABLES ===
  { name: "Carrots", emoji: "🥕", category: "Vegetables",
    dog: { safety: "safe", note: "Excellent crunchy treat! Great for dental health, low calorie, and packed with beta-carotene." },
    cat: { safety: "safe", note: "Cooked carrots are easier to digest. A decent source of vitamins." }},
  { name: "Broccoli", emoji: "🥦", category: "Vegetables",
    dog: { safety: "caution", note: "Safe in small quantities. Too much can cause gas and GI irritation due to isothiocyanates." },
    cat: { safety: "safe", note: "Non-toxic and nutritious. Steam or chop small for easier eating." }},
  { name: "Green Beans", emoji: "🫘", category: "Vegetables",
    dog: { safety: "safe", note: "An ideal healthy treat! Low calorie, high fiber. Plain only — no salt or seasoning." },
    cat: { safety: "safe", note: "Plain green beans are a safe, low-calorie snack." }},
  { name: "Onions", emoji: "🧅", category: "Vegetables",
    dog: { safety: "deadly", note: "HIGHLY TOXIC. Damages red blood cells causing anemia. All forms dangerous — raw, cooked, powder." },
    cat: { safety: "deadly", note: "EXTREMELY TOXIC to cats — even more sensitive than dogs. Can be fatal. Emergency vet immediately." }},
  { name: "Garlic", emoji: "🧄", category: "Vegetables",
    dog: { safety: "toxic", note: "Toxic to dogs — 5x more potent than onions. Causes anemia. Avoid all forms including garlic powder." },
    cat: { safety: "deadly", note: "EXTREMELY TOXIC. Cats are especially sensitive. Even small amounts can cause serious anemia." }},
  { name: "Sweet Potatoes", emoji: "🍠", category: "Vegetables",
    dog: { safety: "safe", note: "Cooked sweet potato is excellent! High in fiber, vitamins A, B6, and C. Never feed raw." },
    cat: { safety: "safe", note: "Cooked sweet potato in small amounts is fine. A good fiber source." }},
  { name: "Pumpkin", emoji: "🎃", category: "Vegetables",
    dog: { safety: "safe", note: "Plain canned pumpkin (not pie filling) is amazing for digestion. Helps with both diarrhea and constipation." },
    cat: { safety: "safe", note: "Plain pumpkin is great for digestive health. Start with 1 teaspoon." }},
  { name: "Mushrooms", emoji: "🍄", category: "Vegetables",
    dog: { safety: "caution", note: "Store-bought mushrooms are safe. NEVER let dogs eat wild mushrooms — many are fatally toxic." },
    cat: { safety: "caution", note: "Store-bought are generally safe. Wild mushrooms can be deadly." }},
  { name: "Corn", emoji: "🌽", category: "Vegetables",
    dog: { safety: "caution", note: "Kernels are safe. NEVER give the cob — it's a serious choking/blockage hazard." },
    cat: { safety: "safe", note: "Small amounts of plain corn kernels are fine. Not very nutritious for cats." }},
  { name: "Peas", emoji: "🟢", category: "Vegetables",
    dog: { safety: "safe", note: "Green peas are a healthy treat packed with vitamins. Avoid canned peas (high sodium)." },
    cat: { safety: "safe", note: "Plain peas are safe and sometimes found in commercial cat foods." }},
  { name: "Spinach", emoji: "🥬", category: "Vegetables",
    dog: { safety: "caution", note: "Small amounts are fine and nutritious. High oxalic acid can cause kidney issues in large amounts." },
    cat: { safety: "caution", note: "Avoid if your cat has urinary or kidney issues. Small amounts otherwise okay." }},
  { name: "Celery", emoji: "🥬", category: "Vegetables",
    dog: { safety: "safe", note: "Low-calorie, crunchy treat that can freshen breath. Cut into small pieces." },
    cat: { safety: "safe", note: "Safe but most cats aren't interested. Fine as an occasional snack." }},
  { name: "Tomatoes", emoji: "🍅", category: "Vegetables",
    dog: { safety: "caution", note: "Ripe red tomatoes are okay in small amounts. Green tomatoes, stems, and leaves are toxic (solanine)." },
    cat: { safety: "caution", note: "Ripe flesh only in tiny amounts. Green parts contain toxic solanine." }},

  // === PROTEINS ===
  { name: "Chicken", emoji: "🍗", category: "Proteins",
    dog: { safety: "safe", note: "Plain cooked chicken is excellent! No bones (cooked bones splinter), no seasoning, no skin." },
    cat: { safety: "safe", note: "Plain cooked chicken is a great protein source. No bones, no seasoning." }},
  { name: "Salmon", emoji: "🐟", category: "Proteins",
    dog: { safety: "safe", note: "Cooked salmon is fantastic — rich in omega-3s. NEVER feed raw salmon (can contain fatal parasites)." },
    cat: { safety: "safe", note: "Cooked salmon is excellent for cats. Rich in omega-3s. Never raw." }},
  { name: "Eggs", emoji: "🥚", category: "Proteins",
    dog: { safety: "safe", note: "Fully cooked eggs are a great protein source. Scrambled or hard-boiled, no seasoning." },
    cat: { safety: "safe", note: "Cooked eggs are safe and nutritious. Avoid raw eggs (salmonella risk)." }},
  { name: "Tuna", emoji: "🐟", category: "Proteins",
    dog: { safety: "caution", note: "Small amounts of plain tuna are okay. Too much can lead to mercury poisoning." },
    cat: { safety: "caution", note: "Cats love it but too much causes mercury buildup and nutritional imbalances. Occasional treat only." }},
  { name: "Raw Meat", emoji: "🥩", category: "Proteins",
    dog: { safety: "caution", note: "Risk of salmonella and E. coli. If feeding raw, follow strict food safety protocols." },
    cat: { safety: "caution", note: "Cats can handle raw meat better than dogs, but bacterial contamination is still a risk." }},
  { name: "Liver", emoji: "🫀", category: "Proteins",
    dog: { safety: "caution", note: "Highly nutritious in small amounts. Too much causes Vitamin A toxicity — limit to 5% of diet." },
    cat: { safety: "caution", note: "Small amounts are beneficial. Excess liver can cause Vitamin A toxicity." }},
  { name: "Turkey", emoji: "🦃", category: "Proteins",
    dog: { safety: "safe", note: "Plain cooked turkey (no skin, bones, or seasoning) is a lean protein treat." },
    cat: { safety: "safe", note: "Plain cooked turkey is safe. Skip the skin and seasoning." }},
  { name: "Shrimp", emoji: "🦐", category: "Proteins",
    dog: { safety: "safe", note: "Fully cooked, deveined, and shell removed. Good source of protein and nutrients." },
    cat: { safety: "safe", note: "Cooked, peeled shrimp is a safe treat cats usually love." }},

  // === DAIRY ===
  { name: "Cheese", emoji: "🧀", category: "Dairy",
    dog: { safety: "caution", note: "Small amounts of low-fat cheese are fine. Many dogs are lactose intolerant — watch for GI upset." },
    cat: { safety: "caution", note: "Most cats are lactose intolerant. Small amounts of hard cheese are better tolerated." }},
  { name: "Milk", emoji: "🥛", category: "Dairy",
    dog: { safety: "caution", note: "Many dogs are lactose intolerant. Small amounts may be okay, but can cause diarrhea and gas." },
    cat: { safety: "caution", note: "Despite the stereotype, most adult cats are lactose intolerant. Use cat-specific milk instead." }},
  { name: "Yogurt", emoji: "🥣", category: "Dairy",
    dog: { safety: "safe", note: "Plain, unsweetened yogurt is great — probiotics aid digestion. NEVER sugar-free (xylitol is toxic)." },
    cat: { safety: "caution", note: "Small amounts of plain yogurt may be tolerated. Watch for digestive upset." }},
  { name: "Ice Cream", emoji: "🍦", category: "Dairy",
    dog: { safety: "caution", note: "High in sugar and lactose. Not toxic but can cause stomach upset. Check for xylitol." },
    cat: { safety: "caution", note: "Too much sugar and lactose for cats. Not recommended." }},

  // === PANTRY / OTHER ===
  { name: "Chocolate", emoji: "🍫", category: "Pantry",
    dog: { safety: "deadly", note: "EXTREMELY TOXIC. Contains theobromine. Dark chocolate is worst. Any amount is dangerous — emergency vet NOW." },
    cat: { safety: "deadly", note: "EXTREMELY TOXIC. Contains theobromine and caffeine. Seek emergency care immediately." }},
  { name: "Xylitol (Sweetener)", emoji: "🧂", category: "Pantry",
    dog: { safety: "deadly", note: "FATALLY TOXIC. Found in sugar-free gum, candy, peanut butter. Causes rapid insulin release and liver failure." },
    cat: { safety: "toxic", note: "Toxic to cats. Found in sugar-free products. Keep all xylitol products away from pets." }},
  { name: "Peanut Butter", emoji: "🥜", category: "Pantry",
    dog: { safety: "safe", note: "Dogs love it! CHECK THE LABEL for xylitol first. Plain, unsalted, xylitol-free PB only." },
    cat: { safety: "caution", note: "Not toxic but high in fat. Check for xylitol. Not very beneficial for cats." }},
  { name: "Honey", emoji: "🍯", category: "Pantry",
    dog: { safety: "caution", note: "Small amounts are safe for adult dogs. Not for puppies (botulism risk). High in sugar." },
    cat: { safety: "caution", note: "Not toxic but very sugary. Cats can't taste sweetness so there's no benefit." }},
  { name: "Bread", emoji: "🍞", category: "Pantry",
    dog: { safety: "caution", note: "Plain bread in small amounts is okay. No nutritional value. Raw dough is DANGEROUS (expands in stomach)." },
    cat: { safety: "caution", note: "Small amounts are harmless. No nutritional benefit. Keep raw dough away." }},
  { name: "Rice", emoji: "🍚", category: "Pantry",
    dog: { safety: "safe", note: "Plain cooked rice is great for upset stomachs. White rice is easier to digest than brown." },
    cat: { safety: "safe", note: "Plain cooked rice is safe. Sometimes used to help with digestive issues." }},
  { name: "Coffee", emoji: "☕", category: "Pantry",
    dog: { safety: "deadly", note: "TOXIC. Caffeine is dangerous for dogs. Symptoms: hyperactivity, seizures, rapid heart rate. Seek vet care." },
    cat: { safety: "deadly", note: "TOXIC. Even small amounts of caffeine can be life-threatening to cats." }},
  { name: "Alcohol", emoji: "🍺", category: "Pantry",
    dog: { safety: "deadly", note: "EXTREMELY DANGEROUS. Even small amounts cause vomiting, diarrhea, CNS depression, coma, and death." },
    cat: { safety: "deadly", note: "EXTREMELY DANGEROUS. Cats are even more sensitive than dogs. Any amount is an emergency." }},
  { name: "Macadamia Nuts", emoji: "🥜", category: "Pantry",
    dog: { safety: "toxic", note: "Causes weakness, vomiting, tremors, and hyperthermia in dogs. Effects usually resolve in 48 hours." },
    cat: { safety: "toxic", note: "Can cause lethargy, vomiting, and tremors. Keep away from cats." }},
  { name: "Almonds", emoji: "🥜", category: "Pantry",
    dog: { safety: "caution", note: "Not toxic but hard to digest and a choking hazard. Salted almonds can cause water retention." },
    cat: { safety: "caution", note: "Not toxic but not easily digested. Can cause GI upset." }},
  { name: "Cinnamon", emoji: "🫙", category: "Pantry",
    dog: { safety: "caution", note: "Small amounts won't harm but can irritate the mouth. Cinnamon powder can cause breathing issues if inhaled." },
    cat: { safety: "toxic", note: "Cats lack the liver enzyme to process cinnamon compounds. Can cause liver damage." }},
  { name: "Salt", emoji: "🧂", category: "Pantry",
    dog: { safety: "toxic", note: "Excessive salt causes sodium ion poisoning: vomiting, diarrhea, seizures. Keep salty snacks away." },
    cat: { safety: "toxic", note: "Cats are very sensitive to excess sodium. Can lead to poisoning and kidney issues." }},
];

export const CATEGORIES = [...new Set(FOOD_DATABASE.map(f => f.category))];
